import type { FaqItem } from '@/lib/schema';

export const colourPredictionFaqs: FaqItem[] = [
  {
    question: 'How does Sikkim Game Colour Prediction work?',
    answer:
      'Each round runs on a fixed timer. Before the timer ends, you choose a colour option, and once the round closes, a result is shown based on the platform\'s outcome logic. Payout multipliers vary by the colour and platform rules in place at the time.',
  },
  {
    question: 'Is Colour Prediction based on skill or chance?',
    answer:
      'Colour Prediction is a chance-based game — outcomes are generated by the platform\'s system rather than skill. Treat it as entertainment with real financial risk, not a guaranteed income method.',
  },
  {
    question: 'What is the minimum bet for Colour Prediction?',
    answer:
      'Minimum and maximum bet amounts are set by the official platform and can change over time. Check the current round rules in the app before placing a bet.',
  },
  {
    question: 'Are there patterns or "tricks" to predict colours?',
    answer:
      'Be very skeptical of any paid "formula", "signal group", or "prediction software" claiming guaranteed wins — these are common scam tactics in this game category and cannot reliably beat a chance-based system.',
  },
  {
    question: 'Can I lose money playing Colour Prediction?',
    answer:
      'Yes. Like any real-money prediction or betting game, you can lose the amount wagered. Only consider playing with money you can afford to lose, and set a personal limit before you start.',
  },
];
