import type { FaqItem } from '@/lib/schema';

export const disclaimerSections = [
  {
    title: 'Independent, unofficial resource',
    body: 'sikkimgame.co.in is not the game developer, operator, payment processor, or any government body. We publish guides and explainers only — we do not run any game round, and no part of this site processes a deposit, bet, or withdrawal.',
  },
  {
    title: 'No connection to the Government of Sikkim',
    body: 'The word "Sikkim" appears here only because that is the common player name for this game category. This site carries no endorsement, license, or backing from the Government of Sikkim or any other state authority.',
  },
  {
    title: 'Real financial risk',
    body: 'Wingo, Colour Prediction and similar formats are real-money, chance-based games. You can lose the amount you wager. Nothing on this site is a guarantee of winnings, and no "strategy" article changes that a result is generated by the platform\'s own system.',
  },
  {
    title: 'Age and eligibility',
    body: 'Everything referenced here is intended for users 18 years or older who are legally permitted to take part in real-money gaming under the rules that apply where they live. Confirm your local regulations before registering or funding an account.',
  },
  {
    title: 'Affiliate relationships',
    body: 'Some outbound links, including registration links, are affiliate links. We may earn a commission if you sign up through them, at no extra cost to you. This arrangement does not change what we write or recommend.',
  },
  {
    title: 'Accuracy over time',
    body: 'App layouts, bonus terms, and game rules can change on the official platform without notice. We update our guides regularly, but always confirm live details in the app itself before relying on anything published here.',
  },
  {
    title: 'No liability for third-party platforms',
    body: 'Once you leave sikkimgame.co.in for the official operator\'s platform, that platform\'s own terms, security, and practices apply. We accept no liability for issues arising from your use of that platform.',
  },
];

export const disclaimerFaqs: FaqItem[] = [
  {
    question: 'Does reading this site mean I am playing through sikkimgame.co.in?',
    answer:
      'No. All gameplay, accounts and money movement happen exclusively on the official operator platform. This site only publishes independent guides and links out to that platform.',
  },
  {
    question: 'If I lose money following your guide, is this site responsible?',
    answer:
      'No. Our guides explain mechanics and process, not outcomes. Any financial result from playing a chance-based game is between you and the official platform, governed by its own terms.',
  },
];
