import type { FaqItem } from '@/lib/schema';

export const vortexFaqs: FaqItem[] = [
  {
    question: 'What is Sikkim Game Vortex?',
    answer:
      'A crash-style game using the same rising-multiplier, cash-out-before-crash mechanic as Aviator, wrapped in a spinning vortex visual instead of a plane.',
  },
  {
    question: 'What does the 96.79% RTP mean?',
    answer:
      'Averaged over a large number of rounds, about 96.79% of money wagered on Vortex is returned to players collectively — close to Aviator\'s 96.55% and Chicken Road 2\'s 97.03%, since all three share the same underlying crash-game structure.',
  },
  {
    question: 'Does the vortex visual affect the odds?',
    answer:
      'No. The animation is cosmetic. The crash point is generated by the same type of independent, round-by-round system used across every crash-style game on the platform — no visual cue predicts it in advance.',
  },
];
