import type { FaqItem } from '@/lib/schema';

export const wingoFaqs: FaqItem[] = [
  {
    question: 'What is Wingo in Sikkim Game?',
    answer:
      'Wingo is a fast-paced number and colour guessing game mode. Players pick a number, a colour, or a size (big/small) before the round timer ends, and a result is revealed once it closes.',
  },
  {
    question: 'How long does one Wingo round last?',
    answer:
      'Round length is set by the official platform and can vary (commonly short intervals of around 1–3 minutes), letting players see results and start a new round quickly.',
  },
  {
    question: 'What can I bet on in Wingo?',
    answer:
      'Typical options include a specific number, a colour associated with that round\'s number set, or a size category such as big or small. Each option has different odds and payout multipliers set by the platform.',
  },
  {
    question: 'Is there a strategy to win at Wingo?',
    answer:
      'Wingo results are generated by the platform\'s system, so no betting pattern guarantees a win. Treat any paid "Wingo strategy" or "prediction tool" claim with skepticism.',
  },
  {
    question: 'What is the difference between Wingo and Colour Prediction?',
    answer:
      'They are closely related game formats. Wingo usually centers on numbers with associated colours and size options, while Colour Prediction focuses purely on picking a colour each round. Rules and terminology can vary by platform version.',
  },
];
