import type { Metadata } from 'next';
import { buildMetadata } from '@/lib/seo';
import { Breadcrumb } from '@/components/layout/Breadcrumb';
import { PageHero } from '@/components/layout/PageHero';
import { Section, SectionHeading } from '@/components/ui/Section';
import { Card } from '@/components/ui/Card';
import { FaqAccordion } from '@/components/ui/FaqAccordion';
import { CtaBand } from '@/components/home/CtaBand';
import { CtaButton } from '@/components/ui/Button';
import { WingoBoardIllustration } from '@/components/home/WingoBoard';
import { ShieldIcon, GridIcon, ZapIcon } from '@/components/icons';
import { wingoFaqs } from '@/lib/content/wingo';

export const metadata: Metadata = buildMetadata({
  title: 'Sikkim Game Wingo — How to Play & Game Rules',
  description:
    'Learn how Sikkim Game Wingo works: number, colour and size betting explained, round timers, and responsible play tips.',
  path: '/wingo',
  keywords: ['Sikkim Game Wingo', 'Sikkim Game Wingo Game'],
});

export default function WingoPage() {
  return (
    <>
      <Breadcrumb items={[{ name: 'Home', path: '/' }, { name: 'Wingo', path: '/wingo' }]} />
      <PageHero
        eyebrow="Sikkim Game Wingo"
        title="Sikkim Game Wingo: How the Game Works"
        intro="Wingo is one of the most popular Sikkim Game modes. Here's what the numbers, colours and size options mean, and how a round plays out."
      />

      <Section>
        <div className="grid gap-10 lg:grid-cols-[1fr_280px] lg:items-start">
          <div>
            <SectionHeading eyebrow="Game format" title="Understanding a Wingo round" />
            <div className="space-y-4 text-sm leading-relaxed text-slate-300">
              <p>
                Each Wingo round centers on a set of numbers, typically 0–9. Before the round timer
                ends, players choose a bet type — a specific number, an associated colour, or a
                size category such as big (usually 5–9) or small (usually 0–4). When the timer hits
                zero, a result number is revealed, and payouts are calculated based on which bet
                types matched.
              </p>
              <p>
                Because rounds run back-to-back on a short timer, Wingo feels fast and continuous
                compared to slower lottery draws. That speed is also why it&apos;s important to set
                a personal budget beforehand rather than chasing losses across many quick rounds.
              </p>
            </div>
            <div className="mt-8 grid gap-5 sm:grid-cols-2">
              <Card>
                <GridIcon className="h-7 w-7 text-neon-400" />
                <h3 className="mt-3 text-base font-semibold text-white">Number, colour & size bets</h3>
                <p className="mt-2 text-sm text-slate-300">
                  Each bet type carries different odds and multipliers — the app displays the
                  current payout table before you confirm a bet.
                </p>
              </Card>
              <Card>
                <ZapIcon className="h-7 w-7 text-neon-400" />
                <h3 className="mt-3 text-base font-semibold text-white">Quick round cycles</h3>
                <p className="mt-2 text-sm text-slate-300">
                  New rounds start immediately after the previous one closes, so results come in
                  fast succession.
                </p>
              </Card>
            </div>
          </div>
          <WingoBoardIllustration />
        </div>
      </Section>

      <Section className="border-t border-white/5 bg-navy-900/40">
        <SectionHeading eyebrow="Play responsibly" title="Set limits before you play Wingo" />
        <Card glass className="max-w-3xl">
          <ShieldIcon className="h-8 w-8 text-neon-400" />
          <p className="mt-3 text-sm leading-relaxed text-slate-300">
            Because Wingo rounds move quickly, it&apos;s easy to play many rounds in a short time.
            Decide on a maximum amount you&apos;re willing to spend before you start, and stop once
            you reach it — regardless of whether recent rounds were wins or losses. Ignore any
            third party offering a paid &quot;Wingo trick&quot; or &quot;prediction bot&quot;; results are generated by
            the platform&apos;s system and cannot be reliably predicted.
          </p>
        </Card>
      </Section>

      <Section id="faq">
        <SectionHeading eyebrow="FAQs" title="Sikkim Game Wingo — Frequently Asked Questions" />
        <FaqAccordion items={wingoFaqs} />
      </Section>

      <Section>
        <CtaBand
          title="Ready to try Wingo?"
          subtitle="Register or log in on the official app to explore the current Wingo rounds."
        />
        <div className="mt-6 flex justify-center">
          <CtaButton href="/colour-prediction" external={false} variant="ghost" showArrow>
            Also see: Sikkim Game Colour Prediction guide
          </CtaButton>
        </div>
      </Section>
    </>
  );
}
